### ISSUE TITLE
Make `Observation` mutable?

### ISSUE THREAD

**Issue by findmyway** [JuliaReinforcementLearning/ReinforcementLearningEnvironments.jl#20]
Making `Observation` mutable can allow hooks to modify observations on the fly. But I'm not sure if it is a good design to do so.

**Comment by zsunberg** [comment]
It seems like this should be immutable. First, in my experience, mutability can have significant performance costs because it is harder for the compiler to reason about the lifetime of the object, and I don't see much advantage to making this simple container. Second, immutable objects encourage people to write code in a more functional style that is easier to understand. Third, if this is mutable and a user wants to save a history of observations, you will constantly have to make copies because you can never be sure someone else won't mutate the object.

**Comment by findmyway** [comment]
Thanks for sharing your experience! So let's remain the `Observation` immutable.
